// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Loner1024/uniix.io/configs"
	"github.com/Loner1024/uniix.io/internal/domain/blog"
	"github.com/Loner1024/uniix.io/internal/server"
	"github.com/Loner1024/uniix.io/internal/services"
	"github.com/Loner1024/uniix.io/internal/store/firebase"
)

// Injectors from wire.go:

func wireApp(config configs.Config) (*server.Server, error) {
	repo := firebase.NewStore()
	useCase := blog.NewUseCase(repo)
	service := services.NewService(useCase)
	serverServer := server.NewServer(service, config)
	return serverServer, nil
}
